### ISSUE TITLE
CI for nbm-maven-plugin

### ISSUE THREAD

**Issue by ebarboni** [mojohaus/nbm-maven-plugin#12]
Hi Milos, 
 I find that there a some mojohaus plugin on travis CI at  https://travis-ci.org/mojohaus.

 Would be nice to have nbm related plugin there.

**Comment by mkleint** [comment]
Hey, I've set it up right after merging your integration tests. I didn't know about travis at mojohaus, I've setup a build at codeship (https://codeship.com/projects/98910) where I already have a previous project. The main page (readme) should have a link to the Ci build as well.

**Comment by ebarboni** [comment]
Sorry didn"t see the codeship stamp. Access is denied but if it's green I guess it means OK.
