### ISSUE TITLE
Update to harness 8.2

### ISSUE THREAD

**Issue by phansson** [mojohaus/nbm-maven-plugin#20]
Now that NetBeans 8.2 is out the plugin should be updated to use the harness from version 8.2 rather than the harness from version 8.1.

(just in case there has been any bug fixes done on the harness from 8.1 to 8.2)

**Comment by ebarboni** [comment]
I add a PR on the nbm-maven-harness plugin. It will need a release after merge so we can update this plugin

**Comment by mkleint** [comment]
I've merged the PR and released the RELEASE82 of the harness artifact. it should reach central in a few hours time. Can you test your application with the new harness? I believe it's done by setting the <dependency> inside <plugin> section.

**Comment by phansson** [comment]
I can see the new version of the `nbm-maven-harness` in Maven Central. Check.

I've executed a test where I've overridden the harness dependency on the plugin:

```
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>nbm-maven-plugin</artifactId>
                    <version>4.1</version>
                    <extensions>true</extensions>
                    <configuration>
                        <brandingToken>${brandingToken}</brandingToken>
                        <cluster>${brandingToken}</cluster>
                        <useOSGiDependencies>true</useOSGiDependencies>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>nbm-maven-harness</artifactId>
                            <version>8.2</version>
                        </dependency>
                    </dependencies>
                </plugin>
```

I've then executed the `build-installers` goal. It all looks ok to me. I can see Maven is downloading the 8.2 harness. However when it comes to the unpacked harness in `target` dir I cannot really tell the difference from the 8.1 harness, so I just have to trust that it is indeed the 8.2 harness being used.

**Comment by mkleint** [comment]
I assume this issue is fixed?
