### ISSUE TITLE
after upgrade netbeans, 

### ISSUE THREAD

**Issue by mcheung63** [mojohaus/nbm-maven-plugin#25]
After upgrade netbeans, i can't run my module, i tried reinstall the netbeans, but same. This is my pom.xml https://github.com/mcheung63/netbeans-minimap/blob/master/pom.xml

Warning - could not install some modules: Minimap - The module Editor Library 2 was requested in implementation version "55" but only "56" was found.

Thanks

**Comment by mkleint** [comment]
please check netbeans module system documentation on implementation dependencies. These depend on very specific versions and an upgrade renders them unsatisfied. Exactly what the message says. So either stay on the old version or bump your implementation dependency version of 'editor library 2'. There is no way with implementation dependencies to support 2 versions at once.
