### ISSUE TITLE
Cannot merge nbm files into autoupdate site: 

### ISSUE THREAD

**Issue by ramiswailem** [mojohaus/nbm-maven-plugin#36]
I can't compile a branding module with this maven version 2.4-SNAPSHOT.

Product Version: Apache NetBeans IDE Dev (Build incubator-netbeans-release-268-on-20180411)
Java: 9.0.4; Java HotSpot(TM) 64-Bit Server VM 9.0.4+11
Runtime: Java(TM) SE Runtime Environment 9.0.4+11
System: Mac OS X version 10.13.4 running on x86_64; UTF-8; en_DE (nb)
User directory: /Users/rami/Library/Application Support/NetBeans/dev
Cache directory: /Users/rami/Library/Caches/NetBeans/dev

cd /Users/rami/NetBeansProjects/mavenproject1; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home M2_HOME=/usr/local/apache-maven-SNAPSHOT /usr/local/apache-maven-SNAPSHOT/bin/mvn -DskipTests=true clean install
Scanning for projects...
------------------------------------------------------------------------
Reactor Build Order:

mavenproject1-parent                                               [pom]
mavenproject1-branding                                             [nbm]
mavenproject1-app                                      [nbm-application]

---------------< org.swailem.rubin:mavenproject1-parent >---------------
Building mavenproject1-parent 9.00.0405                            [1/3]
--------------------------------[ pom ]---------------------------------

--- maven-clean-plugin:2.5:clean (default-clean) @ mavenproject1-parent ---

--- maven-install-plugin:2.4:install (default-install) @ mavenproject1-parent ---
Installing /Users/rami/NetBeansProjects/mavenproject1/pom.xml to /Users/rami/.m2/repository/org/swailem/rubin/mavenproject1-parent/9.00.0405/mavenproject1-parent-9.00.0405.pom

--------------< org.swailem.rubin:mavenproject1-branding >--------------
Building mavenproject1-branding 9.00.0405                          [2/3]
--------------------------------[ nbm ]---------------------------------

--- maven-clean-plugin:2.5:clean (default-clean) @ mavenproject1-branding ---

--- maven-resources-plugin:2.3:resources (default-resources) @ mavenproject1-branding ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 1 resource

--- maven-compiler-plugin:3.7.1-SNAPSHOT:compile (default-compile) @ mavenproject1-branding ---
No sources to compile

--- nbm-maven-plugin:4.2-SNAPSHOT:manifest (default-manifest) @ mavenproject1-branding ---
NBM Plugin generates manifest

--- maven-resources-plugin:2.3:testResources (default-testResources) @ mavenproject1-branding ---
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /Users/rami/NetBeansProjects/mavenproject1/branding/src/test/resources

--- maven-compiler-plugin:3.7.1-SNAPSHOT:testCompile (default-testCompile) @ mavenproject1-branding ---
No sources to compile

--- maven-surefire-plugin:2.19.1:test (default-test) @ mavenproject1-branding ---
Tests are skipped.

--- maven-jar-plugin:2.4:jar (default-jar) @ mavenproject1-branding ---
Building jar: /Users/rami/NetBeansProjects/mavenproject1/branding/target/mavenproject1-branding-9.00.0405.jar

--- nbm-maven-plugin:4.2-SNAPSHOT:branding (default-branding) @ mavenproject1-branding ---
Building jar: /Users/rami/NetBeansProjects/mavenproject1/branding/target/nbm/netbeans/mavenproject1/core/locale/core_mavenproject1.jar
Building jar: /Users/rami/NetBeansProjects/mavenproject1/branding/target/nbm/netbeans/mavenproject1/modules/locale/org-netbeans-core-windows_mavenproject1.jar
Building jar: /Users/rami/NetBeansProjects/mavenproject1/branding/target/nbm/netbeans/mavenproject1/modules/locale/org-netbeans-core_mavenproject1.jar

--- nbm-maven-plugin:4.2-SNAPSHOT:nbm (default-nbm) @ mavenproject1-branding ---
Copying module JAR to /Users/rami/NetBeansProjects/mavenproject1/branding/target/nbm/netbeans/mavenproject1/modules
Generating Auto Update information for org.swailem.rubin.mavenproject1.branding
Cannot find keystore file at /Users/rami/NetBeansProjects/mavenproject1/keystore.pkcs12
No updater.jar specified, cannot validate Info.xml against DTD
Building jar: /Users/rami/NetBeansProjects/mavenproject1/branding/target/nbm/mavenproject1-branding-9.00.0405.nbm

--- nbm-maven-plugin:4.2-SNAPSHOT:autoupdate (updatesite) @ mavenproject1-branding ---
------------------------------------------------------------------------
Reactor Summary:

mavenproject1-parent 9.00.0405 ..................... SUCCESS [  0.215 s]
mavenproject1-branding ............................. FAILURE [  2.339 s]
mavenproject1-app 9.00.0405 ........................ SKIPPED
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 3.797 s
Finished at: 2018-04-16T16:38:17+02:00
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:4.2-SNAPSHOT:autoupdate (updatesite) on project mavenproject1-branding: Cannot merge nbm files into autoupdate site: 
/Users/rami/NetBeansProjects/mavenproject1/target does not exist. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

After correcting the problems, you can resume the build with the command
  mvn <goals> -rf :mavenproject1-branding

[mavenproject1.zip](https://github.com/mojohaus/nbm-maven-plugin/files/1915769/mavenproject1.zip)

**Comment by ebarboni** [comment]
@ramiswailem Hi, it would be nice to rerun with -X to have full debug. What did you run as goal ? 
I cannot reproduce (missing parent pom [org.swailem.rubin:suite;9.00.0405])

**Comment by ramiswailem** [comment]
@ebarboni sorry my mistake. I can't reproduce it
