### ISSUE TITLE
Unable to debug application

### ISSUE THREAD

**Issue by jGauravGupta** [mojohaus/nbm-maven-plugin#40]
Using `mvn nbm:run-ide -Dnetbeans.run.params.debug=true` command shows error in log `Unknown option -Xdebug`  and debugger port connection refused.

**Environment :** 
NetBeans Module version : RELEASE82
nbm-maven-plugin version : 4.1

**Comment by jGauravGupta** [comment]
Also if applying the configuration : 
````
     <properties>
        <nbm.cluster>sample</nbm.cluster>
        <nbm.build.dir>${root.dir}/../external_clusters</nbm.build.dir>
    </properties>
......
     <configuration>
             <cluster>${nbm.cluster}</cluster>
              <nbmBuildDir>${nbm.build.dir}</nbmBuildDir>
              <clusterBuildDir>${nbm.build.dir}/netbeans</clusterBuildDir>
      </configuration>
````

then following error shown : 

````
Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:4.1:cluster (default-cli) on project mavenproject20: The NetBeans binary directory structure for com.mycompany:mavenproject20:nbm:1.0-SNAPSHOT is not created yet.
Please execute 'mvn install nbm:cluster' to build all relevant projects in the reactor.
````
Looks like a issue @ Line#84 https://github.com/mojohaus/nbm-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/nbm/CreateClusterMojo.java#L84

**Comment by MaSven** [comment]
You can also add debugAddtionalArguments to the config. I always give this argument to the netbeans platform to remote debug it.
```
<configuration>
  <debugAdditionalArguments>
-J"-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y"
  </debugAdditionalArguments>
</configuration>
```
After that it should wait for remote debugging
