### ISSUE TITLE
Hyphens in dependencies silently generate corrupted manifest

### ISSUE THREAD

**Issue by timboudreau** [mojohaus/nbm-maven-plugin#41]
I mavenized a bunch of ant-based NetBeans modules, using some scripting to generate the initial POM files; and used `<configuration><moduleDependencies>` to specify specification versions of things.

Not knowing it was the wrong thing to do, the generation tool used the artifactId rather than the module code-name - so, hyphen-separated module names instead of dot-separated, like this:

```xml
                        <dependency>
                            <id>org.netbeans.api:org-openide-util-lookup</id>
                            <type>spec</type>
                            <explicitValue>8.0</explicitValue>
                        </dependency>
```

Trying to run one of these modules resulted in the inscrutable error `Malformed dot-separated identifier: 9.0` on startup.  So I took a look at the manifest of the module JAR I had built, and found:

```
penIDE-Module-Module-Dependencies: 9.0, 8.0, 8.0, 8.0, 1.4, 1.6, org.
 netbeans.modules.editor.lib/3 > 4.7.1.23.3.55, 1.0, 1.0, org.netbeans
 .modules.editor.settings.storage/1 = 201609300101, 1.3, 6.6, 6.2, 6.2
 , 9.0, org.openide.loaders > 7.66.1, 6.2, org.openide.options > 6.37.
 1, 6.16, 6.2
```

as you can see, the code names of all of the modules are simply missing.

The right thing is probably:

 * Fail rather than generate such a manifest
 * Translate dashes to dots if found in `<moduleDependencies>` - anyone using Maven is going to expect to use the artifactId, and hyphens are common there, so the doing the intuitive thing actually works as expected
 * Make sure the docs state clearly what is expected - I've been writing NetBeans plugins for 19 years and I made the wrong assumption - surely others will too

**Comment by timboudreau** [comment]
Ugh.  So, if you correct the pom file to, say,

```
                       <dependency>
                            <id>org.netbeans.api:org-openide-util-lookup</id>
                            <type>spec</type>
                            <explicitValue>8.0</explicitValue>
                        </dependency>
```

for a module with an implementation dependency, then you get a manifest which is not trashed, but the build will fail because of using non-public classes - because the id is no longer matched with the module, so `AbstractNbmMojo.getModuleDependencyArtifacts()` throws them away, since `dash-separated-id` != `dot-separated-id`.

So perhaps the bug is just in how the manifest section is generated, period?

**Comment by mkleint** [comment]
please read documentation on moduleDependencies parameter. http://www.mojohaus.org/nbm-maven-plugin/manifest-mojo.html#moduleDependencies
if 'explicitValue' is defined, it's taken at face value and the 'type' is ignored. you have to specify the entire dependency token (including the module name). so in your case it would be 'org.openide.util.lookup > 8.0'. If type is defined, the actual version number is computed from the dependency's manifest content.
