### ISSUE TITLE
No console output when running NB Platform app on Java 9 or 10

### ISSUE THREAD

**Issue by eirikbakke** [mojohaus/nbm-maven-plugin#45]
I have a maven-based NetBeans Platform app now using the 9.0-vc3 version of the platform libraries. During development, I'm running the application from the IDE, which works fine on Java 8.

However, when I switch to Java 9 or Java 10, there is no console output from the platform application shown in the output pane of the IDE, except for the initial build messages. So nothing that is printed via "System.out.println()" or logged via Logger from the application itself is shown in the IDE's Output pane. If I run the application manually from the Windows command line, without involving nbm-maven-plugin, all messages show up just fine.

The problem occurs regardless of whether Compile-on-Save is enabled or not.

There was a similar bug several years ago: https://netbeans.org/bugzilla/show_bug.cgi?id=235193 . That one could be fixed by using a newer version of the nbm-maven-plugin. This time I'm already at the latest version. And cloning the latest development version of nbm-maven-plugin (commit 1210ee5d1395) and using that one did not help either.

The IDE console output is as follows:

```
cd Z:\Ultorg\ultorg_src\Modules\desktop-application; "JAVA_HOME=C:\\Program Files\\Zulu\\zulu-10.0.2" cmd /c "\"\"C:\\Program Files\\NetBeans\\incubating-9.0-vc3-eb3-pr504\\java\\maven\\bin\\mvn.cmd\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans\\incubating-9.0-vc3-eb3-pr504\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 nbm:cluster-app nbm:run-platform\""
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Ultorg Desktop Application master-SNAPSHOT
------------------------------------------------------------------------

--- nbm-maven-plugin:4.1:cluster-app (default-cli) @ desktop-application ---
Cannot find cluster for C:\Users\ebakke\.m2\repository\com\ultorg\libwrap\hibernate\5.2.16.Final\hibernate-5.2.16.Final.nbm Falling back to default value - 'extra'.
<some more "Cannot find cluster" messages here>
Cannot find cluster for C:\Users\ebakke\.m2\repository\com\ultorg\libwrap\jdbc-mssql\6.2.2.jre8\jdbc-mssql-6.2.2.jre8.nbm Falling back to default value - 'extra'.
Could not resolve Class-Path item in org.netbeans.api:org-netbeans-libs-javafx:nbm-file:RELEASE90VC3EB3, path is:${java.home}/lib/ext/jfxrt.jar, skipping
Integrity verification passed.
Created NetBeans module cluster(s) at Z:\Ultorg\ultorg_src\Modules\desktop-application\target\ultorg

--- nbm-maven-plugin:4.1:run-platform (default-cli) @ desktop-application ---
Executing: cmd.exe /X /C "Z:\Ultorg\ultorg_src\Modules\desktop-application\target\ultorg\bin\ultorg.exe --console suppress --userdir Z:\Ultorg\ultorg_src\Modules\desktop-application\target\userdir -J-Dnetbeans.logger.console=true -J-ea --branding ultorg --jdkhome "C:\Program Files\Zulu\zulu-10.0.2""
<no more messages; expected messages from the application here>
```

I understand from the other bugzilla report that was mentioned before that the " --console suppress" parameter is included intentionally, because console output is supposed to be transmitted by some other means when using the nbm-maven-plugin.

**Comment by geertjanw** [comment]
So this is related to the nbm-maven-plugin, i.e., something needs to be changed inside the nbm-maven-plugin for this?

**Comment by eirikbakke** [comment]
I _suspect_ it is, because there was a similar bug in 2013 that could be fixed by updating the version of nbm-maven-plugin. Not entirely sure, though.

**Comment by eirikbakke** [comment]
Figured it out and added a pull request.

**Comment by geertjanw** [comment]
Awesome.

**Comment by ebarboni** [comment]
Nice. 
We want to start in a near future to call a vote to donate to apache netbeans all the maven related stuff. 
If you have an apache icla it would be ok to merge now. (no major IP clearance issue)
 Otherwise we should wait a few day and maybe redo the pr on a future git at apache for this plugin.

**Comment by eirikbakke** [comment]
Fixed by https://github.com/apache/incubator-netbeans-mavenutils/commit/3b08a5951212f3d09bc24e16ff39411d7d3ac473 after the repo was moved to Apache; closing.
