### ISSUE TITLE
Disabled module type missing details for when is active

### ISSUE THREAD

**Issue by javydreamercsw** [mojohaus/nbm-maven-plugin#5]
I tried to configure a module as disabled, and that works fine, but there's no way to declare how it'll behave after being enabled. Seems like they would be normal by default, but I might need them to be eager.

Not saying is an issue in the plugin, might be an API thing.

http://www.mojohaus.org/nbm-maven-plugin/manifest-mojo.html#moduleType

**Comment by mkleint** [comment]
if the module is to be enabled/disabled manually by the user, it cannot be eager (enables automatically when all it's dependencies are satisfied) nor autoload (enables when some other module depends on it).

as far as I understand things, this is working 'as expected'

**Comment by javydreamercsw** [comment]
What I meant is having a module disabled but that behaves as eager when enabled (i.e. to register on lookup, etc)

Or that's not needed?

**Comment by mkleint** [comment]
"behaves as eager when enabled".. afaik eager module _is_ disabled when dependencies are missing, cannot be enable/disabled manually. If you manually enable/disable, you cannot have eager functionality.
