### ISSUE TITLE
Skip zipping of Runtime

### ISSUE THREAD

**Issue by oxCoffe** [mojohaus/nbm-maven-plugin#51]
Is there a way to skip the zip process of the application?

**Comment by ebarboni** [comment]
@oxCoffe project is migrated to Apache Netbeans (incubating). I would suggest asking question on the user mailing list users@netbeans.apache.org

**Comment by pnabbefeld** [comment]
@ebarboni Will this plugin be migrated, too?

@oxCoffe AFAIK, the maven-jar-plugin is used for zipping - probably You can just skip that?

**Comment by oxCoffe** [comment]
Yea is figured out how to skip it. I just excluded the goal from all phases. I will close this now. But it would be good to have a skipZip option for this plugin. If i'am building in my dev enviroment i dont need to zip this. Would id be ok to add something like this? I could do a PR for this.

**Comment by ebarboni** [comment]
https://github.com/apache/incubator-netbeans-mavenutils/ will be the new home.
a few lib and plugin as well as archetype will be migrated.

it would be appreciated that you create an issue https://issues.apache.org/jira/projects/NETBEANS  using the component mavenutilities and eventually create a PR (I'ts good to have an Apache iCLA).
